apiVersion: v1
kind: Service
metadata:
  name: prwebapi
  labels:
    app: prwebapi
    run: prwebapi
spec:
  ports:
  - name: 80tcp55550-prwebapi
    port: 80
    protocol: TCP
    targetPort: 80
  type: ClusterIP